#!/usr/bin/env bash

#        _          _ ____  _____ _     _
#   __ _| |__   ___/ |___ \|___ /(_) __| | abc123id
#  / _` | '_ \ / __| | __) | |_ \| |/ _` | dumbhighrank
# | (_| | |_) | (__| |/ __/ ___) | | (_| | "mag"
#  \__,_|_.__/ \___|_|_____|____/|_|\__,_| the dragon

## Original Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

## General ---------------------------------------------------#
# NOTE: This configuration is abridged for me.
## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Exports
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'
export BROWSER=firefox
export SXHKD_SHELL='bash'
export _JAVA_AWT_WM_NONREPARENTING=1

## Current theme ---------------------------------------------#

## Border colors
BSPWM_FBC='#7E9CD8'
BSPWM_NBC='#1F1F28'
BSPWM_ABC='#C0A36E'
BSPWM_PFC='#76946A'

## BSPWM visual functions
BSPWM_BORDER='2'
BSPWM_GAP='10'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manage Monitors and Workspaces
##
## Default Setup (Set 8 workspaces on each monitor)
default_workspaces() {
	for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
		bspc monitor "$monitor" -d -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
	done
}

## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
two_monitors_workspaces() {
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	INTERNAL_MONITOR="eDP1"
	EXTERNAL_MONITOR="HDMI-1-0"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '1' '2' '3' '4' '5'
		bspc monitor "$INTERNAL_MONITOR" -d '6' '7' '8' '9' '10'
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
	fi
}

## Uncomment only one function according to your needs
#default_workspaces
two_monitors_workspaces

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"
bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle false
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

## Always Floating Apps
declare -a floating=(Galculator kitty-float plattenalbum zenity minecraft-launcher Pcmanfm Thunar steam Nitrogen Music Pavucontrol kweather Onboard Yad 'Firefox:Places'
	Viewnior feh Nm-connection-editor calamares Calamares)
for i in ${floating[@]}; do
	bspc rule -a $i state=floating follow=on focus=on
done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd openrgb dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Nvidia stuff
nvidia-settings --load-config-only

# Restore wallpaper
bash ~/.fehbg

# Start mpd
exec mpd &

# Start OpenRGB
openrgb --startminimized

# Start libinput-gestures for trackpad gestures
libinput-gestures &

# Start bspwm scripts
bspbar
bspcomp
bspdunst
bspfloat &
