#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
STYLE="onedark"
RASI="$DIR/themes/$STYLE/rofi/asroot.rasi"

# Theme Elements
prompt='Root'
mesg="Run Applications As Root"
term='kitty --class kitty-float --config /root/.config/bspwm/kitty/kitty.conf'

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
	option_1=" Kitty"
	option_2=" Thunar"
	option_3=" Neovide"
	option_4=" Ranger"
	option_5=" Nvim"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		bspasroot "$term"
	elif [[ "$1" == '--opt2' ]]; then
		bspasroot 'dbus-run-session thunar'
	elif [[ "$1" == '--opt3' ]]; then
		bspasroot neovide
	elif [[ "$1" == '--opt4' ]]; then
		bspasroot "$term -e ranger"
	elif [[ "$1" == '--opt5' ]]; then
		bspasroot "$term -e nvim"
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
	run_cmd --opt1
	;;
$option_2)
	run_cmd --opt2
	;;
$option_3)
	run_cmd --opt3
	;;
$option_4)
	run_cmd --opt4
	;;
$option_5)
	run_cmd --opt5
	;;
esac
