## Colors configuration
[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[colors.normal]
black   = "#16161D"
red     = "#C34043"
green   = "#76946A"
yellow  = "#C0A36E"
blue    = "#7E9CD8"
magenta = "#957FB8"
cyan    = "#6A9589"
white   = "#C8C093"

[colors.bright]
black   = "#727169"
red     = "#E82424"
green   = "#98BB6C"
yellow  = "#E6C384"
blue    = "#7FB4CA"
magenta = "#938AA9"
cyan    = "#7AA89F"
white   = "#DCD7BA"
